FROM node:18-alpine

LABEL maintainer="muzammil-irfan"

WORKDIR /code/

# Install Next.js Globally
RUN npm install -g next

# Copy package files first to leverage caching
COPY package*.json ./

# Install dependencies (including Next.js locally)
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npm", "run", "dev"]